/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-13 13:49:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web.bm;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class treeFolder_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
               javax.servlet.jsp.tagext.DynamicAttributes {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/WEB-INF/tags/bm/include.jsp", Long.valueOf(1507901620741L));
    _jspx_dependants.put("jar:file:/C:/Users/wws-li/gitUportalRepo/uPortal/server/apache-tomcat-9.0.0.M26/webapps/BookmarksPortlet/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098707490000L));
    _jspx_dependants.put("file:/C:/Users/wws-li/gitUportalRepo/uPortal/server/apache-tomcat-9.0.0.M26/shared/lib/pluto-taglib.jar", Long.valueOf(1507901631659L));
    _jspx_dependants.put("jar:file:/C:/Users/wws-li/gitUportalRepo/uPortal/server/apache-tomcat-9.0.0.M26/webapps/BookmarksPortlet/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098707490000L));
    _jspx_dependants.put("jar:file:/C:/Users/wws-li/gitUportalRepo/uPortal/server/apache-tomcat-9.0.0.M26/webapps/BookmarksPortlet/WEB-INF/lib/spring-webmvc-3.2.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1419926808000L));
    _jspx_dependants.put("/WEB-INF/uwfn.tld", Long.valueOf(1507901620744L));
    _jspx_dependants.put("jar:file:/C:/Users/wws-li/gitUportalRepo/uPortal/server/apache-tomcat-9.0.0.M26/webapps/BookmarksPortlet/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098707490000L));
    _jspx_dependants.put("jar:file:/C:/Users/wws-li/gitUportalRepo/uPortal/server/apache-tomcat-9.0.0.M26/webapps/BookmarksPortlet/WEB-INF/lib/spring-webmvc-3.2.13.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1419926808000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.13.RELEASE.jar", Long.valueOf(1507901620730L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1507901620735L));
    _jspx_dependants.put("jar:file:/C:/Users/wws-li/gitUportalRepo/uPortal/server/apache-tomcat-9.0.0.M26/shared/lib/pluto-taglib.jar!/META-INF/portlet_2_0.tld", Long.valueOf(1345819646000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.util.HashMap _jspx_dynamic_attrs = new java.util.HashMap();
  private java.lang.String treeName;
  private java.util.Collection entries;
  private java.lang.String parentIdPath;
  private java.lang.String namespace;
  private java.lang.String cssClass;
  private java.lang.String folderIdSuffix;
  private java.lang.String isVFolder;

  public java.lang.String getTreeName() {
    return this.treeName;
  }

  public void setTreeName(java.lang.String treeName) {
    this.treeName = treeName;
    jspContext.setAttribute("treeName", treeName);
  }

  public java.util.Collection getEntries() {
    return this.entries;
  }

  public void setEntries(java.util.Collection entries) {
    this.entries = entries;
    jspContext.setAttribute("entries", entries);
  }

  public java.lang.String getParentIdPath() {
    return this.parentIdPath;
  }

  public void setParentIdPath(java.lang.String parentIdPath) {
    this.parentIdPath = parentIdPath;
    jspContext.setAttribute("parentIdPath", parentIdPath);
  }

  public java.lang.String getNamespace() {
    return this.namespace;
  }

  public void setNamespace(java.lang.String namespace) {
    this.namespace = namespace;
    jspContext.setAttribute("namespace", namespace);
  }

  public java.lang.String getCssClass() {
    return this.cssClass;
  }

  public void setCssClass(java.lang.String cssClass) {
    this.cssClass = cssClass;
    jspContext.setAttribute("cssClass", cssClass);
  }

  public java.lang.String getFolderIdSuffix() {
    return this.folderIdSuffix;
  }

  public void setFolderIdSuffix(java.lang.String folderIdSuffix) {
    this.folderIdSuffix = folderIdSuffix;
    jspContext.setAttribute("folderIdSuffix", folderIdSuffix);
  }

  public java.lang.String getIsVFolder() {
    return this.isVFolder;
  }

  public void setIsVFolder(java.lang.String isVFolder) {
    this.isVFolder = isVFolder;
    jspContext.setAttribute("isVFolder", isVFolder);
  }

  public void setDynamicAttribute(java.lang.String uri, java.lang.String localName, java.lang.Object value) throws javax.servlet.jsp.JspException {
    if (uri == null)
      _jspx_dynamic_attrs.put(localName, value);
  }
  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fportlet_005fdefineObjects_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
  }
}
